add_ace group.user command.setjob deny
add_ace group.user command.orga deny
add_ace group.user command.cardel deny
add_ace group.user command.car deny
add_ace group.user command.dv deny
add_ace group.user command.setaccountmoney deny
add_ace group.user command.giveaccountmoney deny
add_ace group.user command.giveitem deny
add_ace group.user command.giveweapon deny
add_ace group.user command.clear deny
add_ace group.user command.cls deny
add_ace group.user command.clearinventory deny
add_ace group.user command.clearall deny
add_ace group.user command.clsall deny
add_ace group.user command.clearloadout deny
add_ace group.user command.setgroup deny
add_ace group.user command.save deny
add_ace group.user command.saveall deny
add_ace group.user command.coords deny
add_ace group.user command.tpm deny
add_ace group.user command.goto deny
add_ace group.user command.bring deny
add_ace group.user command.kill deny
add_ace group.user command.freeze deny
add_ace group.user command.unfreeze deny
add_ace group.user command.reviveall deny
add_ace group.user command.noclip deny
add_ace group.user command.players deny
add_ace group.user command.banhistory deny
add_ace group.user command.banner_connecting deny
add_ace group.user command.banner_detail deny
add_ace group.user command.banoffline deny
add_ace group.user command.sqlbanreload deny
add_ace group.user command.sqlbanoffline deny
add_ace group.user command.sqlsearch deny
add_ace group.user command.sqlunban deny
add_ace group.user command.sqlsearch deny
add_ace group.user command.sqlban deny
add_ace group.user command.kick deny
add_ace group.user command.ban deny
add_ace group.user command.annonce deny
add_ace group.user command.annonce deny
add_ace group.user command.cleararea deny
add_ace group.user command.clearped deny
add_ace group.user command.cleartable deny
add_ace group.user command.weather deny
add_ace group.user command.web_baseUrl deny
add_ace group.user command.wait deny
add_ace group.user command.endpoint_add_tcp deny
add_ace group.user command.endpoint_add_udp deny
add_ace group.user command.ensure deny
add_ace group.user command.stop deny
add_ace group.user command.start deny
add_ace group.user command.steam_webApiKey deny
add_ace group.user command.load_server_icon deny
add_ace group.user command.spectate deny
add_ace group.user command.unspectate deny
add_ace group.user command.unban deny
add_ace group.user command.mapname deny
add_ace group.user command.pos deny
add_ace group.user command.pv-cull deny
add_ace group.user command.pv-forget-all deny
add_ace group.user command.pv-num-registered deny
add_ace group.user command.pv-num-spawned deny
add_ace group.user command.pv-save-to-file deny
add_ace group.user command.restart deny
add_ace group.user command.resetnose deny
add_ace group.user command.resetperso deny
add_ace group.user command.refresh deny
add_ace group.user command.reloadinv deny
add_ace group.user command.rcon_password deny
add_ace group.user command.net_tcpConnLimit deny
add_ace group.user command.netlib deny
add_ace group.user command.netPort deny
add_ace group.user command.openPropertymenu deny
add_ace group.user command.openinventory deny
add_ace group.user command.onesync deny
add_ace group.user command.onesync_automaticResend deny
add_ace group.user command.fileserver_add deny
add_ace group.user command.fileserver_list deny
add_ace group.user command.fileserver_remove deny
add_ace group.user command.tags deny
add_ace group.user command.time deny
add_ace group.user command.toggle deny
add_ace group.user command.temp_convar deny
add_ace group.user command.rateLimiter_getinfo_burst deny
add_ace group.user command.rateLimiter_getinfo_rate deny
add_ace group.user command.zoneinfo deny
add_ace group.user command.gamename deny
add_ace group.user command.gametype deny